### ISSUE TITLE
感谢翻译好文，客服提供PDF mobi epub 下载

### ISSUE THREAD

**Issue by yudar1024** [iambowen/cloud-design-patterns#35]
感谢在https://iambowen.gitbooks.io/cloud-design-pattern/content/ 提供翻译的文章。

但是发现没有电子书下载，对于手机查看很不方便，是否可以提供相关格式的下载方面离线浏览。感谢

**Comment by iambowen** [comment]
https://github.com/iambowen/cloud-design-patterns/blob/master/cloud-design-patterns.pdf
